FROM python:3

WORKDIR /usr/src/app

RUN pip install openai
RUN pip install langchain
RUN pip install langchain-openai
RUN pip install beautifulsoup4
RUN pip install faiss-cpu

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8891", "--allow-root" ]